# Generated by Django 2.1.4 on 2019-01-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sex', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cp', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trestbps', models.DecimalField(decimal_places=4, max_digits=10)),
                ('chol', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fbs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('restecg', models.DecimalField(decimal_places=4, max_digits=10)),
                ('thalach', models.DecimalField(decimal_places=4, max_digits=10)),
                ('exang', models.DecimalField(decimal_places=4, max_digits=10)),
                ('oldpeak', models.DecimalField(decimal_places=4, max_digits=10)),
                ('slop', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ca', models.DecimalField(decimal_places=4, max_digits=10)),
                ('thal', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
