# Generated by Django 2.1.4 on 2019-01-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.DecimalField(decimal_places=4, max_digits=10)),
                ('BMI', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Glucose', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Insulin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('HOMA', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Leptin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Adiponectin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Resistin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('MCP1', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
