# Generated by Django 2.1.4 on 2019-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreastCancer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breastcancer',
            old_name='MCP1',
            new_name='Classification',
        ),
        migrations.AddField(
            model_name='breastcancer',
            name='MCP',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
