# Generated by Django 2.1.4 on 2019-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Glucose', models.DecimalField(decimal_places=4, max_digits=6)),
                ('BloodPressure', models.DecimalField(decimal_places=4, max_digits=6)),
                ('SkinThickness', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Insulin', models.DecimalField(decimal_places=4, max_digits=6)),
                ('BMI', models.DecimalField(decimal_places=4, max_digits=6)),
                ('DiabetesPedigreeFunction', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Age', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
