# Generated by Django 2.1.4 on 2019-01-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calories', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Distance', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeightHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Minimum', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Maximum', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
